name: Accessibility Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: qa

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: qa

      - name: Build frontend
        run: npm run build -w frontend
        working-directory: qa

      - name: Serve frontend
        run: |
          npx serve -s dist -l 3000 &
          npx wait-on http://localhost:3000
        working-directory: qa/frontend

      - name: Run Playwright tests
        run: npx playwright test tests/accessibility
        working-directory: qa

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: qa/playwright-report/
          retention-days: 30
